Remove post-install hook
sdkman/sdkman-cli pull request #1155
Opened 2022-12-18 02:12 UTC by hgeraldino

First PR: remove post-install hook

2022-12-22 13:19 UTC, marc0der commented on src/test/resources/features/checksum_verification.feature
> +#	Scenario: Abort installation after download of a binary with invalid MD5 checksum
Curious about why this was commented out. We're still calling the `__sdkman_checksum` function above in `sdkman-install.sh`. Was this perhaps causing some failure?

2022-12-22 13:21 UTC, marc0der commented on src/test/resources/features/pre_and_post_installation_hooks.feature
> +#		And a "post" install hook is served for "grails" "2.1.0" on "Linux" with architecture "x86_64" that returns successfully
Is it worth stripping this out of the step defs if we're not longer going to us it?

2022-12-22 13:22 UTC, marc0der commented on src/test/resources/features/pre_and_post_installation_hooks.feature
> +#	Scenario: Post-install Hook returns a non-zero code
I guess we can delete this one completely.

2022-12-22 13:24 UTC, marc0der commented on src/test/resources/features/pre_and_post_installation_hooks.feature
> +#	Scenario: Post-install Hook returns a non-zero code
On second thought, I think this entire feature file and all it's related step defs can go. I also suggest ripping out the pre-install hooks as part of this. We no longer use those either.

2022-12-22 13:26 UTC, marc0der requested changes
Looking good! I think we can rip out the nasty pre-installation hooks too, since we don't use them anymore.

2022-12-22 16:03 UTC, marc0der commented on src/test/resources/features/checksum_verification.feature
> +#	Scenario: Abort installation after download of a binary with invalid MD5 checksum
Don't worry, just saw the follow up PR :smile:

2022-12-22 16:04 UTC, marc0der commented on src/test/resources/features/java_installation.feature
> +#	Scenario: Platform is supported and a specific version of compatible binary is installed
Same as before, please ignore this.

2022-12-26 16:12 UTC, hgeraldino commented
> Looking good! I think we can rip out the nasty pre-installation hooks too, since we don't use them anymore.

Removed

2022-12-26 17:33 UTC, marc0der approved these changes

2022-12-27 01:21 UTC, merged