Improved error message when candidate version not found
sdkman/sdkman-cli pull request #859
Opened 2021-01-27 12:51 UTC by gerrytan

The message now adds an `sdk install` command to inform user how to correct the error.

This is useful when auto env is enabled, and user not aware their colleague has updated the candidate version. In some situation user isn't even aware of the presence of sdkman. All they see was just `Stop! java 15.0.2.fx is not installed`.

See more discussion about this PR in [this Slack thread](https://sdkman.slack.com/archives/CJK9DMV6V/p1611405973006900)

2021-01-27 20:21 UTC, marc0der requested changes
I realised that someone else recently did something [very similar](https://github.com/sdkman/sdkman-cli/blob/f6ee7927c77f351cbe6765e886099b286a841103/src/main/bash/sdkman-env-helpers.sh#L87) for Java installations.

How about we mimic this for the sake of consistent behaviour?

Also, take note that we are using different colouring:
* red for the initial alert message
* yellow for the information that follows.

2021-01-27 20:21 UTC, marc0der commented on src/test/resources/features/default_version.feature
> +		And I see ""
This line can be dropped.

2021-01-27 20:21 UTC, marc0der commented on src/test/resources/features/home.feature
> +		And I see ""
As before

2021-01-27 20:21 UTC, marc0der commented on src/test/resources/features/use_version.feature
> +		And I see ""
As before

2021-01-28 12:38 UTC, gerrytan commented on src/test/resources/features/default_version.feature
> +		And I see ""
TIL, fixed, thanks!

2021-01-28 12:38 UTC, gerrytan commented on src/test/resources/features/home.feature
> +		And I see ""
Fixed

2021-01-28 12:38 UTC, gerrytan commented on src/test/resources/features/use_version.feature
> +		And I see ""
Fixed

2021-01-28 12:42 UTC, gerrytan commented
> Hi @gerrytan! Firstly, thanks so much for your contribution. This helps everyone so much, so keep them coming!
> 
> I realised that someone else recently did something [very similar](https://github.com/sdkman/sdkman-cli/blob/f6ee7927c77f351cbe6765e886099b286a841103/src/main/bash/sdkman-env-helpers.sh#L87) for Java installations.
> 
> How about we mimic this for the sake of consistent behaviour?
> 
> Also, take note that we are using different colouring:
> 
> * red for the initial alert message
> * yellow for the information that follows.
> 
> Sorry for messing you around like this, I'd forgotten about the tip in the Java installation.
> And again, thanks!

No problem at all, I have pushed this commit to address the above feedback: 8983b488d1f388a6277e2ca9f81eb58f3c7b68f6

2021-02-03 22:23 UTC, marc0der approved these changes
Great work, thanks for contributing!

2021-02-03 22:23 UTC, merged

2021-02-04 01:30 UTC, gerrytan commented
> Great work, thanks for contributing!

Woohoo! Thanks for your help @marc0der!